I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


The label fin_chasse is defined twice, at
  File "game/genovore.rpy", line 241 and
  File "game/genovore.rpy", line 270.

Ren'Py Version: Ren'Py 7.3.5.606
Tue Oct 13 21:40:38 2020
