I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/patriarche.rpy", line 115, in script
    $ texteReperage = CycleReperageCulte()
  File "game/patriarche.rpy", line 115, in <module>
    $ texteReperage = CycleReperageCulte()
  File "game/script.rpy", line 86, in CycleReperageCulte
    if niveauReperage > reperageMax and not enqueteArbites:
UnboundLocalError: local variable 'enqueteArbites' referenced before assignment

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/patriarche.rpy", line 115, in script
    $ texteReperage = CycleReperageCulte()
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/patriarche.rpy", line 115, in <module>
    $ texteReperage = CycleReperageCulte()
  File "game/script.rpy", line 86, in CycleReperageCulte
    if niveauReperage > reperageMax and not enqueteArbites:
UnboundLocalError: local variable 'enqueteArbites' referenced before assignment

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Tyranides 1.0
Thu Oct 22 22:38:12 2020
