I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/genovore.rpy", line 207, in script
    $ nbCycleChasse = nbCycleChasse + 1
  File "game/genovore.rpy", line 207, in <module>
    $ nbCycleChasse = nbCycleChasse + 1
NameError: name 'nbCycleChasse' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/genovore.rpy", line 207, in script
    $ nbCycleChasse = nbCycleChasse + 1
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/genovore.rpy", line 207, in <module>
    $ nbCycleChasse = nbCycleChasse + 1
NameError: name 'nbCycleChasse' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Tyranides 1.0
Sun Oct 11 19:30:48 2020
